DATASET:
    ROOT: "data/st800k_crop"
    NAME: "st800k"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 16
    BATCH_SIZE: 8
    BASE_SIZE: (128,32)
    MODEL_SAVE_DIR: 'workdirs/debug'
TEST:
    BATCH_SIZE: 1
    TEST_MODEL_PATH: 'workdirs/debug/16.pth'

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "TextSeg"
    BACKBONE: "resnet50"

